### ISSUE TITLE
Failed to launch the browser process

### ISSUE THREAD

**Issue by osyahbana** [daxcay/ComfyUI-WA#1]
Hello,

I have the following error when I tried to run it on my Ubuntu 24.04. Here are the error message.
```
/home/ComfyUI/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[0929/215138.546574:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5e3892e5d4e2 base::debug::CollectStackTrace()
#1 0x5e3892dceab3 base::debug::StackTrace::StackTrace()
#2 0x5e3892dcbcf7 logging::LogMessage::~LogMessage()
#3 0x5e38908e30a2 content::ZygoteHostImpl::Init()
#4 0x5e38929178af content::ContentMainRunnerImpl::Initialize()
#5 0x5e3892914f6b content::RunContentProcess()
#6 0x5e38929154fe content::ContentMain()
#7 0x5e38929773c6 headless::(anonymous namespace)::RunContentMain()
#8 0x5e3892977068 headless::HeadlessShellMain()
#9 0x5e388ee601e3 ChromeMain
#10 0x7dbe6362a1ca (/usr/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
#11 0x7dbe6362a28b __libc_start_main
#12 0x5e388ee6002a _start



TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/ComfyUI/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at Interface.<anonymous> (/home/ComfyUI/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
    at Interface.emit (node:events:532:35)
    at Interface.close (node:internal/readline/interface:527:10)
    at Socket.onend (node:internal/readline/interface:253:10)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
``` 

Seems there's an issue in starting the Chromium for puppeteer (for the Whatsapp verification and listening most likely. Could you possibly help me take a look at this? @daxcay 

Appreciate it.

**Comment by daxcay** [comment]
Hi @osyahbana,

Currently, only Windows is supported. I tried to make it compatible with Ubuntu, but I haven't succeeded yet. Chrome on Ubuntu causes a lot of bugs. I forgot to mention this in the documentation.

Sorry for any inconvenience caused.

**Comment by osyahbana** [comment]
No worries, thanks for the plugin regardless. I'll set this git to watched. Thank you.
